---
# sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:  

# TESTED  OK    
    - name: "build gradle w findbugs blackduckcopilot  on bionic arm64"
      dist: bionic
      arch: amd64 
      sudo: required        
      language: java
      jdk:
      - openjdk8
      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.gradle'
      before_install:
        - java -version
        - gradle -v
        # - chmod +x gradlew
        - cd app4 && chmod +x gradlew
      script:
        # - cd app4 && chmod +x gradlew
        - ./gradlew assemble
        - ./gradlew check
      after_success:
        # Upload to CoPilot
        - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
        - deactivate


 # TESTED OK 
    - name: "build gradle w make findbugs blackduckcopilot  on bionic arm64"
      dist: bionic
      arch: amd64 
      sudo: required        
      language: java
      jdk:
      - openjdk8
      cache:
      directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'
      before_install:
        - java -version
        - gradle -v
      script:
        - sudo make deploy-app4
      after_success:
        # Upload to CoPilot
        - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
        - deactivate      
