---
os: linux
dist: bionic
arch: amd64 
sudo: false
notifications:
  email: false
lang: ruby
rvm:
  - 2.4.1
  - 2.5
  - 2.6
  - 2.7
  # - jruby
  # - jruby-9.2
before_install:
  - cd ruby-pipeline/app1
# The command "gem install redcarpet -v '3.5.0' --source 'https://rubygems.org/'" failed and exited with 1 during   
  # - gem install redcarpet -v '3.5.0' --source 'https://rubygems.org/'  
script:
  - bundle exec rake
after_success:
  # Upload to CoPilot
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
  - deactivate
