version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  
  build-virtualenv:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Create virtualenv
          command: |
            python -V
            python3 -V
            pip3 --version
            pip3 install virtualenv
            virtualenv -p $(which python3) ~venvpy3
            source ~venvpy3/bin/activate
            pip install -r requirements.txt
  
  build-gradle:
    docker:
      # the primary container, where your job's commands are run
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo         
    steps:
      - setup_remote_docker        
      - run:
          name: "OS fingerprinting - Debian GNU/Linux 10 (buster) x86_64"
          command: |
            uname -a
            cat /etc/issue
            cat /etc/os-release
      - checkout
      - run:
          name: "build gradle w findbugs blackduckcopilot  on bionic arm64"
          command: |
            echo "=============================build gradle============================================================="
            java -version
            gradle -v
            cd app4 && chmod +x gradlew
            ./gradlew assemble
            ./gradlew check
      - deploy:
          name: "upload copilot"
          command: bash <(curl -s https://copilot.blackducksoftware.com/ci/circle2/scripts/upload)

workflows:
  version: 2
  commit-parallel-workflow:
    jobs:
      - build-virtualenv
      - build-gradle
  scheduled-workflow:
    triggers:
      - schedule:        
          cron: "0 0 1 * *" # once a month
          filters:
            branches:
              only: 
              - main
    jobs:
      - build-virtualenv
      - build-gradle