name: "gradle findbugs blackduckcopilot workflow"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

  linux-job:
    name: "build gradle w findbugs blackduckcopilot"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status
    - name: "build gradle w findbugs blackduckcopilot on - Debian GNU/Linux 10 (buster) x86_64"
      run: |
            echo "=============================build gradle w findbugs blackduckcopilot============================================================="
            java -version
            gradle -v
            cd app4 && chmod +x gradlew
            ./gradlew assemble
            ./gradlew check
            echo "=============================build gradle w findbugs blackduckcopilot============================================================="
    - name: "upload blackduckcopilot"
      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/circle2/scripts/upload)

