# This is a basic workflow to help you get started with Actions

name: osmatrix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status
    - name: "build gradle w findbugs codecov on - Debian GNU/Linux 10 (buster) x86_64"
      run: |
            echo "=============================build gradle w findbugs blackduckcopilot============================================================="
            java -version
            gradle -v
            cd app4 && chmod +x gradlew
            ./gradlew assemble
            ./gradlew check
            echo "=============================build gradle w findbugs blackduckcopilot============================================================="
    - name: "upload blackduckcopilot"
      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/circle2/scripts/upload)

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!